### ISSUE TITLE
proper handling of opening remote files

### ISSUE THREAD

**Issue by digizeph** [bgpkit/bgpkit-parser#1]
Currently, when creating a new parser instance, we automatically retrieve bytes from the remote resources using `reqwest`. We currently do not have proper handling of the situation where the remote resources might not be able to load successfully. 

Specifically, the following `reqwest` call will panic if something goes strange on the remote site:
https://github.com/bgpkit/bgpkit-parser/blob/695fab3849a360aa1778740a6481365858c42543/src/io.rs#L13

**Comment by luminshi** [comment]
A sample error msg when calling `let parser = BgpkitParser::new(SOME_URL)`

```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("data.ris.ripe.net")), port: None, path: "/rrc16/2021.10/updates.20211003.1810.gz", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(5), cause: Some(Io(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" })) }, X509VerifyResult { code: 0, error: "ok" })) }'```
