### ISSUE TITLE
Possible feature: JSON -> CSV

### ISSUE THREAD

**Issue by jfuruness** [bgpkit/bgpkit-parser#142]
I used the JSON option to download RIB dumps into JSON files. I'm wondering if it would be possible to have the same keys as the JSON, but as a header for a CSV or PSV? 

The reason being I'm working on a lot of MRT data, and outputting all the RIB dumps I have as a JSON file takes up too much space for my machine. Additionally, when analyzing the files that get output, it's a lot faster to load in a CSV than it is to load in a JSON. However, I don't want to lose the information provided in all of the JSON keys - it is so incredibly useful!

**Comment by digizeph** [comment]
Can you take a look at PR #145?

**Comment by jfuruness** [comment]
Absolutely, tutoring someone rn but should be able to check it out in an hour or two. Thank you so much!

**Comment by jfuruness** [comment]
I just checked this out, this is totally awesome! Literally twice as fast, and a third the size of the JSON for the same info. It also includes the super nice only_to_customers column, which is super important.

A few questions:

It looks like there’s a few elements that are included in the JSON but not in the PSV. Specifically, origin_asns, peer_asn, peer_ip, deprecated, and unknown. Not critical but would be nice to have.

Also for those elements, what are the deprecated and unknown fields that are present in the JSON? Very curious about these. Same with the origin_asns, I was under the assumption that the last ASN in the path was the origin, or is it something different (perhaps due to AS sets?)

And if those other elements aren’t going to be included no worries, feel free to close the issue and/or merge the PR at any point. Thank you so much for this!

**Comment by jfuruness** [comment]
*edited, I just missed the peer_asn and peer_ip in the PSV header, oops!

**Comment by digizeph** [comment]
To answer your questions:
1. `origin_asns` is a derived field from the AS_PATH. I can put it into the PSV as it is already in `BgpElem`. It is plural due to the existence of AS sets, exactly as you mentioned.
2. `deprecated` and `unknown` are for BGP path attributes that were known to be deprecated or unknown. The data for these fields were not parsed, i.e. remain raw bytes, and not very useful to write to output. It can be processed with Rust SDK if needed.

**Comment by digizeph** [comment]
I added the new `origin_asns` field and tested it with importing the PSV file into sqlite3. See more details here:
https://github.com/bgpkit/bgpkit-parser/pull/145#issuecomment-1843597064

**Comment by jfuruness** [comment]
Super awesome, just tried it out, works great!

Makes sense regarding the deprecated and unknown fields (and origin asns). I think the deprecated and unknown fields might be nice to have for research purposes to be honest, because it might be an interesting result to be able to say X% of MRT Announcements still use deprecated BGP attributes, and those attributes may, in certain ASes, still affect routing decisions. Same with unknown attributes. But really those are just a sidenote to the rest of the information you've provided and are just a nice-to-have not required at all. 

Super cool tool, so glad I came across this, and thanks a ton for providing this information in such a nice and fast way. It has significantly sped up my parsing of MRT announcements.

Feel free to close the issue, thanks again!

**Comment by digizeph** [comment]
Glad that I could help!
