### ISSUE TITLE
Possible Feature: Python wrapper

### ISSUE THREAD

**Issue by jfuruness** [bgpkit/bgpkit-parser#143]
This is an awesome tool in Rust, but a lot of BGP researchers don't know Rust. I wonder if it would be possible to take the code you showed here:

use bgpkit_parser::BgpkitParser;
let parser = BgpkitParser::new("http://archive.routeviews.org/bgpdata/2021.10/UPDATES/updates.20211001.0000.bz2").unwrap();
for elem in parser {
    println!("{}", elem)
}

And simply make this one section to able to be potentially pip installed and imported in python, with some kind of python wrapper around this generator. That would be incredibly useful.

If this should not belong in this repo I totally understand, right now I just download the JSON files and then load those into Python, but being able to skip the write to disk by just loading in Python objects would be very nice (since due to the volume of data it is very slow to write to disk, read to disk, and takes up a ton of space)

**Comment by digizeph** [comment]
You should be able to do `pip3 install pybgpkit` and run the following code:

```
import bgpkit
parser = bgpkit.Parser(url="https://spaces.bgpkit.org/parser/update-example",
                       filters={"peer_ips": "185.1.8.65, 2001:7f8:73:0:3:fa4:0:1"})
count = 0
for elem in parser:
  count += 1
  print(elem)
assert count == 4227
```

See more documentation here: https://github.com/bgpkit/pybgpkit

**Comment by jfuruness** [comment]
Amazing, I'll check it out tonight, closing this issue
