### ISSUE TITLE
Documention update around format

### ISSUE THREAD

**Issue by jfuruness** [bgpkit/bgpkit-parser#144]
Currently the default format is a PSV file that looks similar to the output from bgpdump. Documentation for this output would be great. Similarly for the JSON file, I'm confused how the PSV is converted into the JSON file. 

I think as a short term fix you mentioned merely viewing: https://github.com/bgpkit/bgpkit-parser/blob/33618df32f148aad846cd7aef8cc78e2c49eb422/src/models/bgp/elem.rs#L126

**Comment by digizeph** [comment]
The generation of PSV is manual as you linked there. The JSON output is done automatically by the Rust's `serde` crate. In essence, it takes the content of `BgpElem` struct and convert it to JSON string automatically.

You will have to look at the `BgpElem` fields' types for their conversion details:
```
#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BgpElem {
    pub timestamp: f64,
    #[cfg_attr(feature = "serde", serde(rename = "type"))]
    pub elem_type: ElemType,
    pub peer_ip: IpAddr,
    pub peer_asn: Asn,
    pub prefix: NetworkPrefix,
    pub next_hop: Option<IpAddr>,
    pub as_path: Option<AsPath>,
    pub origin_asns: Option<Vec<Asn>>,
    pub origin: Option<Origin>,
    pub local_pref: Option<u32>,
    pub med: Option<u32>,
    pub communities: Option<Vec<MetaCommunity>>,
    pub atomic: bool,
    pub aggr_asn: Option<Asn>,
    pub aggr_ip: Option<BgpIdentifier>,
    pub only_to_customer: Option<Asn>,
    /// unknown attributes formatted as (TYPE, RAW_BYTES)
    pub unknown: Option<Vec<AttrRaw>>,
    /// deprecated attributes formatted as (TYPE, RAW_BYTES)
    pub deprecated: Option<Vec<AttrRaw>>,
}
```

**Comment by jfuruness** [comment]
Thank you!
