### ISSUE TITLE
bibtex?

### ISSUE THREAD

**Issue by jfuruness** [bgpkit/bgpkit-parser#166]
What do you want the bibtex to be for citations (if you're interested in that)?

**Comment by digizeph** [comment]
Hey @jfuruness thanks for asking! I'm no expert in bibtex, but a `bgpkit-parser` name with a link to this repo would be perfect! For citing for broader bgpkit functions (like broker or data), maybe a link to the `bgpkit` [github org](https://github.com/bgpkit) might suit it better.

Love to give your paper a read when it becomes available!

**Comment by jfuruness** [comment]
Sounds great! I believe I also have to list authors, who should I list for that? Definitely can send along, we're submitting to CCS on April 29th so fingers crossed!

**Comment by digizeph** [comment]
You can have Mingwei Zhang and Jasper Meggitt as the authors. (cc @jmeggitt)

Good luck with your submission! Will close this issue now. Feel free to add more comments in here.

**Comment by jfuruness** [comment]
Thanks I appreciate it!
