### ISSUE TITLE
failed to resolve: use of undeclared crate or module `env_logger`

### ISSUE THREAD

**Issue by Ji-Shao** [bgpkit/bgpkit-parser#189]
cargo build --examples
-- omitted --

error[E0433]: failed to resolve: use of undeclared crate or module `env_logger`
 --> examples/extended_communities.rs:6:35
  |
6 |     env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
  |                                   ^^^^^^^^^^ use of undeclared crate or module `env_logger`

error[E0433]: failed to resolve: use of undeclared crate or module `env_logger`
 --> examples/extended_communities.rs:6:5
  |
6 |     env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
  |     ^^^^^^^^^^ use of undeclared crate or module `env_logger`
  |
help: consider importing one of these structs
  |
1 + use std::thread::Builder;
  |
1 + use kafka::consumer::Builder;
  |
1 + use kafka::producer::Builder;
  |
1 + use tempfile::Builder;
  |
help: if you import `Builder`, refer to it directly
  |
6 -     env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
6 +     Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();
  |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `bgpkit-parser` (example "extended_communities") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by digizeph** [comment]
Thanks for reporting this issue! The `dev-dependencies` is missing `env_logger` crate. Here is a fix:
https://github.com/bgpkit/bgpkit-parser/commit/af25f3f17c1e7910a17387b6559f88496841d604

I've also added a CI task to make sure future commits will not break examples: https://github.com/bgpkit/bgpkit-parser/commit/d8d3baa9529cd10af5291770ce99348a88d048c8

Please let me know if you encounter any other issues. Thanks!
