### ISSUE TITLE
Consider reexporting bgpkit-models

### ISSUE THREAD

**Issue by SZenglein** [bgpkit/bgpkit-parser#55]
Right now you left `bgp-models = "0.7.0-alpha.4"` on an older version. Using the library is a bit cumbersome because you have to use the exact same bgp-models version if you want to do more with it.
For this reason, lots of rust crates reexport their related dependencies.

Also consider bumping the bgp-models version.

**Comment by digizeph** [comment]
Thanks for the suggestion! Re-exporting `bgp-models` is definitely a good suggestion. I will patch it soon!

(Sorry for getting back to you this late! Somehow GitHub by default not sending emails for new issues unless I manually "watch" it.)

**Comment by digizeph** [comment]
(GitHub automatically closes this issue when PR #57 is merged.)

I am in the process of releasing a new minor version for this change. If you still encounter problems after this change, please feel free to re-open this issue.

Thanks!
