### ISSUE TITLE
Add support for std::io::Read

### ISSUE THREAD

**Issue by jmeggitt** [bgpkit/bgpkit-parser#74]
It would be helpful to have support for using `std::io::Read` types directly as input sources when parsing BGP data.

For example, one use-case of this would be parsing BGP messages from non-local or memory sources.
```
let mut http_stream = ureq::get("https://data.ris.ripe.net/rrc00/2022.01/bview.20220126.1600.gz").call()?.into_reader();
process_bgp_msgs(http_stream)?;

// Generic over any given read source
fn process_bgp_msgs<R: Read>(source: R) -> io::Result<()> {
    let mut reader = BgpkitParser::for_reader(source);
    for message in reader {
        // Propogate reader errors
        do_foo(message?);
    }
}
```
Additionally, it would be helpful if this extended to individual BGP messages as well. Functions such as `parse_ris_live_message`, `parse_bmp_msg`, `parse_openbmp_header`, `parse_openbmp_msg`, and `parse_mrt_record` already exist, but take inconsistent or non-standard inputs (`&mut DataBytes`, `&str`, and `T: Read`). Ideally these would all be standardized to accept `T: Read` and/or `&[u8]`.

This change will likely require the complete redesign or removal of `DataBytes` due to its current requirement on reading the entire source into memory before parsing. Supporting a generic `Read` interface could greatly improve memory usage by only loading the data source as it is needed. One possible replacement for `DataBytes` would be using the `byteorder` crate to read big-endian values from a `Read` source and `std::io::Read::take` for limits.

Support for `std::io::Write` could also be helpful, but there are far fewer use-cases for that functionality.

**Comment by digizeph** [comment]
Hey @jmeggitt thanks for the comment!

I have a preliminary patch that changes the `BgpkitParser` to takes in `std::io::Read` as input.
https://github.com/bgpkit/bgpkit-parser/blob/d30bf6f0c6f308276cc060e5877c2df7ec94f8a5/bgpkit-parser/src/parser/mod.rs#L113

The new constructor function `BgpkitParser::new_with_reader(reader)` takes in a `Box<dyn Read>` as the parameter. The example linked above tests both raw reader with uncompressed file, and a bzip decoder with compressed updates file.

I intent to go replace the usage of `DataBytes` with more standard traits, but as you noticed, the change could be quite significant. I will investigate further and get onto it soon.

**Comment by jmeggitt** [comment]
Sounds like a good improvement, but I would lean towards taking (and possibly using) `Read` as a generic. By requiring that the input be a boxed anonymous trait without a lifetime, it means we have to give the parser ownership of the value. In most cases this is not an issue, but in some cases it may require buffering a message before use.

As a hypothetical, lets say I have a couple systems logging notable groups of BGP messages to be investigated later. In addition to the BGP messages, the log also contains some additional metadata on the state of the system at the time. However, since `new_with_reader` requires that requires the reader be a `'static` owned value, I would need to read the entire message section to a buffer before being able to pass it to `BgpkitParser`. This takes additional time to allocate and copy the data and there is a small chance that there would not be enough space to fit a large group of messages.

Ideally it would be possible to do something like this and be able to process log files directly or when received by some controller.
```rust
use std::net::Ipv4Addr;
use byteorder::{ReadBytesExt, BigEndian};
use std::io;
use std::io::Read;
use std::io::ErrorKind::UnexpectedEof;

pub fn parse_bgp_log<R: Read>(reader: &mut R) -> io::Result<()> {
    loop {
        let header = match read_header(reader) {
            Ok(header) => header,
            // Reached end of file
            Err(e) if e.kind() == UnexpectedEof => return Ok(()),
            Err(err) => return Err(err),
        };
        
        let message_parser = BgpkitParser::from_reader(reader.take(header.bytes));
        
        for record in message_parser {
            // Do something with record and header information
        }
    }
}

/// Header with metadata about the data collection proceeding a group of bgp
/// messages
struct Header {
    bgp_server: Ipv4Addr,
    timestamp: u64,
    bytes: u64,
}

fn read_header<R: Read>(reader: &mut R) -> io::Result<Header> {
    // Read the IPv4 address as big endian bytes
    let mut server_address = [0u8; 4];
    reader.read_exact(&mut server_address)?;
    
    // Use the byteorder crate to extract the other values
    Ok(Header {
        bgp_server: Ipv4Addr::from(server_address),
        timestamp: reader.read_u64::<BigEndian>()?,
        bytes: reader.read_u64::<BigEndian>()?,
    })
}
```

To give a better idea of what I am describing, I created a [gist](https://gist.github.com/jmeggitt/b6ed95064beb990e819871d00fcfb946) with the modified file with what I am proposing for `bgpkit-parser/bgpkit-parser/src/parser/mod.rs`.

**Comment by jmeggitt** [comment]
Additionally, I noticed 2 minor issues in [bgpkit-parser/bgpkit-parser/src/parser/mod.rs](https://github.com/bgpkit/bgpkit-parser/blob/d30bf6f0c6f308276cc060e5877c2df7ec94f8a5/bgpkit-parser/src/parser/mod.rs#L113). I suspect `cargo clippy` would have found at least one of them, but I thought it may be worth mentioning.

Inside `new_with_reader`, it creates a second unnecessary box.
```rust
pub fn new_with_reader(reader: Box<dyn Read>) -> Result<BgpkitParser, ParserErrorWithBytes>{
    Ok(
        BgpkitParser {
            // reader is already boxed so boxing it again just adds unnecessary indirection
            reader: Box::new(reader),
            core_dump: false,
            filters: vec![],
            options: ParserOptions::default()
        }
    )
}
```

Also, since `Box<dyn Read>` is not `Send` this introduces the possibility of undefined behavior by allowing non-send values to be moved and subsequently accessed on different threads. It should be simple to remove the need for this line by replacing `Box<dyn Read>` with `Box<dyn Read + Send>` to the anonymous trait be `Send` as well.
https://github.com/bgpkit/bgpkit-parser/blob/d30bf6f0c6f308276cc060e5877c2df7ec94f8a5/bgpkit-parser/src/parser/mod.rs#L40

**Comment by digizeph** [comment]
Hey @jmeggitt, here is my current attempt on getting rid of `DataBytes` in favor of `[u8]` and `std::io::Cursor<&[u8]>` directly. The code change is quite large as it revolves changes all over the places.
https://github.com/bgpkit/bgpkit-parser/pull/80

Per your point above:
```
However, since new_with_reader requires that requires the reader be a 'static owned value, I would need to read the entire message section to a buffer before being able to pass it to BgpkitParser.
```
You do not need to read entire message section to a buffer before passing it to parser. In fact, none of the current examples require one to read all the bytes first before parsing. For example, currently when reading from a remote source, it takes a [`reqwest::Response`](https://docs.rs/reqwest/0.11.13/reqwest/struct.Response.html#) which starts as soon as the connection establishes. In this way, you can start parsing a 1+GB RIB dump files immediately without waiting for it to download.

I hope that makes sense.

**Comment by jmeggitt** [comment]
@digizeph, That sounds like a great improvement. A single message at a time should not be an issue for memory. Being able to parse a message from a `&[u8]` without allocating a new `Vec<u8>` every time is also be a great improvement since it allows a single buffer to be re-used for messages.

My concern above was that `BgpkitParser` consumes the reader so it is not possible to then take the reader back and read non-MRT data. By allowing it to consume a mutable reference to a `Read` type (via `reader.take(header.bytes)` in the example), it would allow the caller to take back control of the reader after the reference expired. As you stated, this would not be an issue for RIB dump files which do not contain non-MRT data mixed in. I believe this change will be simple to apply and will largely only require changes to `bgpkit-parser/bgpkit-parser/src/parser/mod.rs` when combined with your work in #80. Later today I will try to implement this functionality and create a pull request for it.

Additionally, I was trying to see how easy it would be to remove/replace `DataBytes` with a completely generic `Read` instance a while ago. I ran into a couple issues (mostly due to not being able to rewind the `Read` position) and did not get very far, but I did re-implement `ReadUtils` to be a bit more efficient. I'm not sure if this will be helpful, but you can find that work at https://github.com/bgpkit/bgpkit-parser/compare/main...jmeggitt:bgpkit-parser:read-api. Thankfully, I think you can avoid the issues I encountered though due to your usage of `Cursor<&[u8]>`.
