### ISSUE TITLE
Caching MRT files

### ISSUE THREAD

**Issue by mikolaj-kow** [bgpkit/bgpkit-parser#96]
Greetings, 
I've been testing the parser (via python bindings) and broker (local instance) for past few days.
It is working great so far, but when testing workflows again and again for the same query, it seems that MRT dumps are downloaded multiple times, which is quite inefficient. 

I noticed that oneio already implements `get_cache_reader` function. Do you think it is possible to use it in bgpkit-parser?

The BGPStream implements such functionality and in allows to save time and bandwidth. 

Thank you for your time

**Comment by digizeph** [comment]
Thanks for using our parser!

Yes, current design does not utilize the cache feature from `oneio` library at the moment. I took a quick look at the implementation, and I believe I can add a new constructor function to use `get_cache_reader` instead.

Since this sounds like a relatively straightforward feature to add, I will bundle it with the `0.9` release that will happen soon.

**Comment by mikolaj-kow** [comment]
That is great, thank you.

**Comment by digizeph** [comment]
PR #99 adds the new `new_cached` constructor for parser. We will get the python version updated later.

**Comment by digizeph** [comment]
Hi @mikolaj-kow, I have some good news! Both`pybgpkit` and `pybgpkit-parser` V0.4.0 are released with support for specifying a `cache_dir` when creating a new `Parser` instance. Here is a example using `pybgpkit` package:
```python
from bgpkit import Parser
import json

parser = Parser(
    url="https://spaces.bgpkit.org/parser/update-example",
    filters={"peer_ips": "185.1.8.65, 2001:7f8:73:0:3:fa4:0:1"},
    cache_dir="./"
)

for elem in parser:
    print(elem["origin_asns"])
    print(json.dumps(elem, indent=4))
    break
```

Please let me know if you have additional questions.

**Comment by mikolaj-kow** [comment]
Thanks @digizeph. I've tested new release. 
Downloading MRTs works for both RIB and updates. The speedup is visible, for the above exemplary code (first and second run):

```
Executed in  704.05 millis    fish           external 
   usr time  166.98 millis    0.00 micros  166.98 millis 
   sys time   39.40 millis  867.00 micros   38.54 millis 

Executed in  177.75 millis    fish           external 
   usr time  144.77 millis    0.00 micros  144.77 millis 
   sys time   33.19 millis  1020.00 micros   32.17 millis 
```

However, it is always downloading into the current working directory, not into the specified `cache_dir`. I've tried relative and absolute path. 

Can you take a second look?

**Comment by digizeph** [comment]
@mikolaj-kow I can reproduce this issue on my end. Investigating now.

**Comment by digizeph** [comment]
Hey @mikolaj-kow, the issue should be fixed in pybgpkit 0.4.1 now. Can you try it out and see if you still encounter any problems?

**Comment by mikolaj-kow** [comment]
Hi, 
It is working as intended now. Thanks!

**Comment by mikolaj-kow** [comment]
Hi, after more thorough testing, I need to reopen the issue.
It looks like a cache file is created/used regardless of the `collector_id`, which leads to bogus results. 

Please see the examples:

```
for item in broker.query(ts_start="2014-04-01 00:00:01", ts_end="2014-04-01 00:04:59", project="riperis", data_type="update", print_url=True):
    elems = Parser(url=item.url,cache_dir="/tmp/data_bgpkit/").parse_all()
    print(f"{item.collector_id} - {len(elems)}")
```
rrc00 - 12818
rrc01 - 12818
rrc03 - 12818
rrc04 - 12818
rrc05 - 12818
rrc06 - 12818
rrc07 - 12818
rrc10 - 12818
rrc11 - 12818
rrc12 - 12818
rrc13 - 12818
rrc14 - 12818
rrc15 - 12818


Expected result (the same query without `cache_dir`):
```
for item in broker.query(ts_start="2014-04-01 00:00:01", ts_end="2014-04-01 00:04:59", project="riperis", data_type="update", print_url=True):
    elems = Parser(url=item.url).parse_all()
    print(f"{item.collector_id} - {len(elems)}")
```
rrc00 - 12818
rrc01 - 14073
rrc03 - 12563
rrc04 - 5717
rrc05 - 7889
rrc06 - 1629
rrc07 - 4337
rrc10 - 4644
rrc11 - 6824
rrc12 - 25975
rrc13 - 11198
rrc14 - 178177
rrc15 - 7923

In the `cache_dir`, there is only one file created  `cache-bf681351-updates.20140401.0000.gz`

BTW I would suggest putting the checksum as a suffix; it would make sorting files much easier.

**Comment by digizeph** [comment]
Will investigate, stay tuned!

**Comment by digizeph** [comment]
@mikolaj-kow using `pybgpkit==0.4.2` should be able fix this issue. I have tested in multiple environments. Also see #103 for the Rust version pull request for the original issue and the fix. Please let me know if you still see any issues. Thanks!

**Comment by mikolaj-kow** [comment]
Hi, 
I've tested the updated version, and it has worked without issue. 
Thank you for implementing this!
